apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-frontend
spec:
  replicas: {{ .Values.canaryReplica }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 'abatan/simplewebapp:{{ .Values.image.tag }}'
        ports:
        - containerPort: 3000